### ISSUE TITLE
Plugin broken from 20150825 commits

### ISSUE THREAD

**Issue by markwaters** [mapkyca/Known2FA#2]
Something in the commits on Aug 25, 2015 have broken your TwoFactorAuth plugin.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/Known2FA/issues/2" class="u-in-reply-to"></a>Seems to work for me, could you give me some more details of what you're seeing?

**Comment by markwaters** [comment]
Sure , if I logout and then try and login again I get the usual username and password page and then the TwoFactorAuth page , this fails to login as usual with :-

You don't have access to this content.
It looks like you don't have permission to view this content. Sorry!

If I roll back with :-
````git reset --hard ff069ea```
Everything works as normal.

**Comment by markwaters** [comment]
The actual commit that breaks it is 
``git reset --hard 2402574``
rolling back to :
``git reset --hard ff069ea``
fixes it again.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/Known2FA/issues/2#issuecomment-135106560" class="u-in-reply-to"></a>Law of unintended consequences. 

Looks like you're losing the referrer somewhere along the line, although I've yet to be able to replicate...

Could you let me know:

1) What server you're running
2) Whether you're accessing it over TLS or not
3) Confirm that it is infact the 2fa plugin or just the referrer problem by disabling the 2fa plugin temporarily on the broken version of Known, logging out and logging back in again.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/Known2FA/issues/2#issuecomment-135122618" class="u-in-reply-to"></a>And browser info might be handy as well...

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/Known2FA/issues/2#event-393177067" class="u-in-reply-to"></a>I notice you closed this issue... is it working for you now?

If not, or you worked around it some way, it'd still be good to know... :)

**Comment by markwaters** [comment]
Sorry , I kept updating the fourth comment as I worked my through it.
I also commented on the Known commit to help anyone else seeing the same problem.
https://github.com/idno/Known/commit/240257487aef956c487a7943ce4132aa160732c0#commitcomment-12910312

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/Known2FA/issues/2#issuecomment-135348673" class="u-in-reply-to"></a>Ahh... didn't see that.. thanks.

Yes, it needs a referrer set - basically the anti-spam stuff stops most script kiddies since they tend to POST directly to the form endpoint, rather than "submitting" the form which (mostly) sets the referrer.

Since doing a similar .htaccess thing on my wordpress install, I've reduced login attempts from thousands a day to 0...
