### ISSUE TITLE
Cursor in entry box

### ISSUE THREAD

**Issue by markwaters** [mapkyca/Known2FA#3]
This is a little thing but it annoys me each time it happens.

After I have entered my username and password I am faced with the two factor page but have to use the mouse (or finger when mobile , not so bad as I am holding for a paste) to click on the entry box to make the cursor appear.

On the twitter web two factor auth page the cursor is waiting in the entry box ready for the code to be entered.

**Comment by mapkyca** [comment]
<a href="" class="u-in-reply-to"></a><a href="https://github.com/mapkyca/Known2FA/issues/3" class="u-in-reply-to"></a>I agree, that's probably something that should be done. Thanks :)

**Comment by markwaters** [comment]
Thank you!
